name: Test
on: [workflow_dispatch]


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: ahmed225522/newMcitCopyRepo@v1
        with:
          who-to-greet: '@octocat'
